language: node_js
node_js:
- 8.11.3
# cache:
#   directories:
#   - node_modules
script:
- npm run build
- npm test
deploy:
  provider: heroku
  api_key:
    secure: R64Bnn+5aPviSF6LiCb4nwA86RG8HXNyx651/SULcchL3+VnmK5uBCJ6a26OHuNS24TzgTDmBXuDkF8BdirSAsC6WmP7pJhn9uE/v7CQd4g2FIZ24WIHQ1UtOpnvFy+xKdvyTbkS/eqCVY80mvTRXnDdyI+jhV8qxMAeYgTe0HahjyolaCq0OnYKLu/aG/K8qB4BMfBH9+5dVkrF+S3W3LBZZpyWolkmCOrGpFtnLCRvcR0Fp5Dgtn3rrHsBhfx1YZaQs2YYU8U/JJQ3hbvCffh63XsqfmmVMGM3cdwpY09psZ/0f5ND41+cRLSGmoq2A0LCCSHTtAz9sQMv0wTPKan02C+C6R2I+acuoTGef3srKkNsFmg1MakEaZRkAQrtV9PJno4OVxTFKP4wj3ySl1g2eXYOYR1583MGFpqAXWP+PzSWW2DpkDOQ8v0UmvkJDlmooHItSYLvrmUeLrAeKFFT+FJceZzoGI0GLlA7IjA1AiYSvqLfkiKEdVP/E94EydWc5Ov9+JW4lVylrSDgWKP1SmeKGJbjW6nCsJlJ3FGW64rQUSIjnE1Dku+qN4+Z9fynkqGjq5WtPHMyMfpVYdVlKh1Sqc0dw2ZfutTR5hbmsMrIu+V4JFJxfX9+rayH2UefX7J+xTNdSZx9fl0f9nmIth1ZRUQTitEovSbc9Wo=
  app: joseph-kerkhof-portfolio
  local_dir: build
