language: node_js
node_js:
- 8.11.3
script:
- npm run build
- npm test
deploy:
  provider: heroku
  api_key:
    secure: SzsMkGW49iPRU0u4lOpkresQha55qejhPRFc44KYKJlu9C7Cl7tJy6sdQ7tkBWNVFXRMzv0ZB16yMV66tsh0aKFFRewq/zMOguQUgkCooxnRurvlgUZdOLME6opiZCrMDEnfEG+IaB0bzFyC3jioru0LNYS1YWt+ASus9D6Lub0PYth1BltufUttZSgV89tnwOskmk0xIBQEAYBa7QccaybPdwPbjG+vcfUDxsvRMF7MgSuETUOkujfHRbasnJ4Vj/G5bxElIyAjNxC4IgbpW7QMrzj11H6lcRDx4mWRfIP9r78UzodVdRWhRJ0YAU/mudEXA1SzYAs6VQJSG50Y3qS6JRphbShEzP2+Ca6TiE4klwiTxdsLDNd66admcwIZaEtv8ljFmZauQ6zSUsAZzOCtvxEGNWEshaQrBP2FP5io5NfGCoQNrMoU+uyVwwD/bo6SBBJCp6DspbZtnLcZhe3Q7rMTLhKIFFCEZTFg5YlgXfdQVkmalFS0JigYnZ44BhTyMbNQZ4I/h9CP9YdY8GHpczr7Q34xUlOh/xtEzRH+lBYpXflXdBCeQuaL87EV10pI0K2/KC9wsRc8iz58UIX0S6EKqVE4EeT97qeBfasvw7lXiDo9owj3ooCRd2SSnms5/yPAdjzlpESP88xjtc7XbROM2WwBAn5e02Yv1g4=
  app: joseph-kerkhof-portfolio
